name: ThePeople
description: 八一八那些名人和名组织的故事
author: jiaj_luo
keywords: 人类 组织 名人 故事

sass:
  sass_dir: assets/css/_sass
  style: :compressed

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "tables", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

url: http://andyljj.github.io/thepeople
permalink: /:year/:month/:title/
owner:
    name: #
    twitter: #
    github: #
    disqus_shortname: #

ga_id: #
ga_username: #

timezone: Africa/Accra